name: task_trackr
description: "Mobile app for field agents to manage location-based tasks with offline support."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0

  # Local Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Location & Maps
  geolocator: ^10.1.0
  flutter_map: ^8.2.2
  geocoding: ^2.1.1

  # Network
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  # dio: ^5.4.0 # For API calls if needed

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Utilities
  intl: ^0.18.1 # Date formatting
  uuid: ^4.2.2
  dartz: ^0.10.1 # Functional programming (Either)
  rxdart: ^0.27.7 # Reactive extensions

  # UI/UX
  cached_network_image: ^3.3.0
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0 # Loading indicators
  shimmer: ^3.0.0 # Skeleton loading
  lottie: ^2.7.0 # Animations

  # Routing
  go_router: ^12.1.3

  # Biometric
  local_auth: ^2.1.7

  # Others
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shimmer_animation: ^2.2.2
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

  # Code Generation
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/